plugins {
    id 'com.android.application'
}

android {
    namespace 'id.fiberix.billing'
    compileSdk 34

    defaultConfig {
        applicationId 'id.fiberix.billing'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
        resValue 'string', 'app_start_url', 'https://fiberix.my.id/login?next=/mobile'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ''
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'com.google.android.material:material:1.12.0'
}
